build_pdf:
  image: pablodecm/pandoc-nodejs:0.0.3
  script:
    - apt-get install -y texlive-science
    - cabal install pandoc-citeproc pandoc-crossref
    - cd paper
    - make  
  artifacts:
    paths:
     - paper/paper.pdf

arxiv:
  image: pablodecm/pandoc-nodejs:0.0.3
  script:
    - apt-get install -y texlive-science wget
    - wget https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.7/binaries/Linux/biber-linux_x86_64.tar.gz
    - export PATH=$PWD:$PATH
    - which biber
    - cabal install pandoc-citeproc pandoc-crossref
    - cd paper
    - make arxiv_tar 
    - make arxiv_pdf  
  artifacts:
    paths:
     - paper/arxiv.tar.gz
     - paper/arxiv/paper.pdf
