build_pdf:
  image: pablodecm/pandoc-nodejs:0.0.2
  script:
    - apt-get install -y texlive-science
    - cabal install pandoc-citeproc pandoc-crossref
    - cd paper
    - make  
  artifacts:
    paths:
     - paper/paper.pdf
