name: inferno-env
channels:
- conda-forge
dependencies:
- python=3.6
- numpy=1.14.5
- matplotlib
- pandas
- jupyter
- tqdm
- scipy
- h5py  
- pip:
  - tensorflow==1.10.1
  - tensorflow-probability==0.3.0
  - corner
  - git+https://github.com/pablodecm/neyman.git
